### ISSUE TITLE
Please add me to your "Professional Services Network"

### ISSUE THREAD

**Issue by gravitonian** [OrderOfTheBee/marketing#17]
Hi,

Company: http://www.marversolutions.com
Me: http://www.marversolutions.com/wordpress/about_us/ 
Blog: http://www.marversolutions.com/wordpress/ecm-stuff-blog/ 
Books: Alfresco 3 Business Solutions, Alfresco CMIS
Territory: UK & Ireland

thanks,
Martin Bergljung

**Comment by aviriel** [comment]
added with https://github.com/OrderOfTheBee/OrderOfTheBee.github.io/commit/8bb46d2c95b584ed78ed031bc1d10b90f934bd6d

**Comment by gravitonian** [comment]
Hi,

You can remove me from the "Professional Service Network" now that I work
for Alfresco.

thanks,
Martin

**Comment by aviriel** [comment]
You make me sad :( Removed with 5c0981cc700784ebf9198138a1ced7a25b9fd85d 
Good luck on the new place. :)
