### ISSUE TITLE
Alfresco Day San Francisco

### ISSUE THREAD

**Issue by alfrescojean** [OrderOfTheBee/marketing#19]
http://pages.alfresco.com/080415-AMER-Event-AlfrescoDaySanFrancisco_EV-Reg-LP.html?mkt_tok=3RkMMJWWfF9wsRomrfCcI63Em2iQPJWpsrB0B%2FDC18kX3RUmIL%2Bcfkz6htBZF5s8TM3DVVdDXrxI%2BkEPTLI%3D

**Comment by CristinaMR** [comment]
Thanks, alfrescojean. Events page updated! 
Issue closed.
