### ISSUE TITLE
Use Alfresco folder rules to perform admin tasks

### ISSUE THREAD

**Issue by Tybion** [OrderOfTheBee/marketing#22]
A new blog for the OOTB Blog of the Day?

You might have seen it when it was published, and it was quite brief, but I have added more detailed information to it since then.

http://geofoss.net/2015/09/17/use-alfresco-folder-rules-to-manage-admin-tasks/

**Comment by aviriel** [comment]
Yep, it became more technical. I'll ad it for tomorrow. Thank you!
