### ISSUE TITLE
Alfresco Lunch & Learns

### ISSUE THREAD

**Issue by khillstead** [OrderOfTheBee/marketing#23]
Hi Ole,

I wanted to share some upcoming Alfresco Lunch & Learn dates with you to post on the OOTB Calendar. The events are free to attend and will be hosted by Alfresco Partners.

Lunch & Learn - Philadelphia, PA
Hosted by Zia Consulting
The Capital Grille
1338 Chestnut Street
Philadelphia, PA 19107
Link to Register: 
https://www.alfresco.com/events/zia-consulting-lunch-learn-philadelphia 

Lunch & Learn - Baltimore, MD
Hosted by Armedia
Baltimore Marriott Inner Harbor
110 S. Eutaw Street
Baltimore, MD 21201
Link to Register: 
https://www.alfresco.com/events/armedia-lunch-learn-baltimore

Lunch & Learn - Dallas, TX
Hosted by Zia Consulting
Perry's Steakhouse and Grill - Uptown
2000 McKinney Avenue, Suite 100
Dallas, TX 75201
Link to Register: 
https://www.alfresco.com/events/zia-consulting-lunch-learn-dallas

Lunch & Learn - Raleigh, NC
Hosted by Armedia
Sheraton Imperial Hotel & Conference Center
4700 Emperor Blvd
Durham, NC 27703
Link to Register: 
https://www.alfresco.com/events/armedia-lunch-learn-raleigh

Lunch & Learn - San Francisco, CA
Hosted by Micro Strategies
Waterbar
399 The Embarcadero
San Francisco, CA 94105
Link to Register: 
https://www.alfresco.com/events/micro-strategies-lunch-learn-san-francisco

Lunch & Learn - Denver, CO
Hosted by Zia Consulting
Venice Ristorante - Denver Tech Center
5944 S. Holly Street
Greenwood Village, CO 80111
Link to Register:
https://www.alfresco.com/events/zia-consulting-lunch-learn-denver

Thanks and have a great weekend!

Kyle

**Comment by aviriel** [comment]
Added these events to the calendar. Thank you Kyle!

**Comment by khillstead** [comment]
Thanks Oksana!

On Oct 24, 2015, at 1:28 PM, Oksana Kurysheva <notifications@github.com<mailto:notifications@github.com>> wrote:

Added these events to the calendar. Thank you Kyle!

##
