### ISSUE TITLE
Professional Services Network

### ISSUE THREAD

**Issue by MajesticComputerTechnology** [OrderOfTheBee/marketing#25]
Hi,
We have been offering alfresco community solutions to our clients since 2012 in Australia and would like to join the professional services network of Order of the Bee.

The link to our website is [http://majesticdev.com.au](). We have also launched a Joomla and Wordpress plugin for displaying content from Alfresco. More details can be found on [https://github.com/MajesticComputerTechnology]().

Please do not hesitate to contact me if you have any questions.

Thank you in anticipation,
Nishant Sony | Software Engineer
Majestic Computer Technology
Studio 21, 477 Warrigal Road,Moorabbin,VIC 3189
Phone: +61 3 9553 3200 | Fax: +61 3 9553 3066
Email: nishant@majestic.com.au | Web: www.majestic.com.au, www.majesticdev.com.au

**Comment by aviriel** [comment]
Thank you for this request! I added information to the website: http://orderofthebee.org/professionals/ with
https://github.com/OrderOfTheBee/OrderOfTheBee.github.io/commit/24271cb89237ba85fbde59726ad94bd9e3e147b4 and https://github.com/OrderOfTheBee/OrderOfTheBee.github.io/commit/969e43d64344d9550de7bbbc4b3a3cbcfdd52e45
If you want to add something, feel free to create new issue or pull request.
