### ISSUE TITLE
Professional Services Network Request

### ISSUE THREAD

**Issue by nattaphon-np** [OrderOfTheBee/marketing#26]
Dear Order of the Bee

I would like to add my company to your Professional Services Network

Company: B Circle Co., Ltd.
Web Site: https://www.bcircle.co.th
Territory: Thailand 

B Circle is a company specialized in document management, document scanning and document workflow based on Alfresco and community version and Activiti. We are very active promote Alfresco to Thailand. 

B Circle can offer you a fast and cost effective
- Our completed Alfresco DMS base on Community 5.x
- Easy capture “Smart scanning for Alfresco”
- Paperless Workflow solution for Alfresco
- Custom Alfresco interface to another system
- Migration a million of document from legacy DMS to Alfresco with advance content model
- Services around analysis, implementation, customization, training and support Alfresco

Alfresco and Document management Knowledge Base 
https://www.bcircle.co.th/knowledge-base/

Youtube Chanel Fee Alfresco Community 5.1 Training and Alfresco Knowledge 
https://www.youtube.com/c/BcircleTh

I alway read blog on Order of the Bee
Thank for everything you done and share about Alfresco. 

Best Regards,

Nattaphon

**Comment by nattaphon-np** [comment]
Sorry for wrong typing 
Free >> Fee

Correct is 
Youtube Chanel Free Alfresco Community 5.1 Training and Alfresco Knowledge 
https://www.youtube.com/c/BcircleTh

Thanks

**Comment by nattaphon-np** [comment]
update contract 
Mr. Nattaphon Neamkasipong 
Consult Director
email: nattaphon.np@bcircle.co.th 
Adress
82/11 Soi Krung ThonBuri 6 Bang Lamphu Khetklong San Bangkok 10600 Thailand
Phone: +66 2 438 8452

**Comment by aviriel** [comment]
Published. We don't publish email and phone, I hope website should be enough.
It would be nice if you open source some your Alfresco extensions or publish some success stories on your implementations of Alfresco Community in the future.

**Comment by nattaphon-np** [comment]
Sorry for publish email and phone I don’t know it should not. 
I will publish some success stories in the future. 

Thanks

**Comment by aviriel** [comment]
> Sorry for publish email and phone I don’t know it should not.

Not a problem. We just don't want to increase a number of spam messages you receive. And we believe that Alfresco users are clever enough to open the website and find the contact information themselves ;)
