### ISSUE TITLE
Want to be added to the professional network 

### ISSUE THREAD

**Issue by shazada** [OrderOfTheBee/marketing#28]
Company: Contezza
Location: The Netherlands
Website: http://www.contezza.nl
Blog: http://www.contezza.nl/blog

Open Repositories:
Alfresco Module to get Email notification on update of content https://github.com/shazada/cntz-document-notification

Free addons:
Alfresco Advanced search in Folder http://www.contezza.nl/store/p19/Alfresco_Share_Folder_Search.html
Youtube Dashlet http://www.contezza.nl/store/p27/YouTube_Dashlet.html
Metadata Export http://www.contezza.nl/store/p25/Alfresco_Metadata_Export.html
Default AND search in Alfresco http://www.contezza.nl/store/p17/Alfresco_Share_%22AND%22_Search.html

**Comment by aviriel** [comment]
Hello Tahir,
Thank you for the submission. I added Contezza to the website. We cannot add a list of free addons the "profile" (they are free but not open, so they don't confirm the quality of the code, they are good for the list of contributions of the person, but don't work for the Professionals Network). All other information is added.

**Comment by shazada** [comment]
Great, thanks!
