### ISSUE TITLE
Zylk.net in Professional Services Network

### ISSUE THREAD

**Issue by CesarCapillas** [OrderOfTheBee/marketing#29]
Zylk.net is an open IT company situated in Bilbao (Spain), specialized in open-source solutions and driving digital transformation for a wide range of clients including private enterprise, public administrations and government bodies across Spain and Europe. Since 2004, we have provided expertise on the design, development and integration of Java open-source enterprise products, specialising in Document Management (Alfresco), Enterprise Portals (Liferay), Big Data (Hortonworks, Hadoop), Business Intelligence (Pentaho) and Digital Signature (Sinadura) solutions. The company has been awarded the ISO20000-1 quality certificate standard for supporting service management systems. 

Zylk team is a Silver partner of Liferay Portal and Hortonworks, with a highly experienced (+6 years) team, trained and certified in Alfresco ECM (ACA and ACE). Zylk is expert in Alfresco integrations and customizations, for example custom authentication subsystems or digital signature addons. The team participates actively in the Alfresco Community, including Alfresco forums and events such Alfresco Meetups, Days and Summits, and recently Beecon. The company blog "No Blogo" features an extensive number of Alfresco-related posts, including technical advice and case studies of Alfresco in enterprise.

**Open Repositories:**
- Edit in Libreoffice Addon --> https://github.com/CesarCapillas/alfresco-share-online-edition-addon
- Send Link by Email --> https://github.com/CesarCapillas/alfresco-share-send-link-by-email 
- CMIS Content Viewer --> https://web.liferay.com/es/marketplace/-/mp/application/23325217
- Sinadura Desktop --> http://www.sinadura.net

**Blog:**
- http://www.zylk.net/es/web/guest/web-2-0/blog

**Website:**
- http://www.zylk.net

**Comment by aviriel** [comment]
Hi Cesar,

Thanks a lot for your submission, I added info to the website: http://orderofthebee.org/professionals/
I didn't add CMIS Content Viewer and Sinadura Desktop to the list of repositories, because actually these links are not to the repositpries, and I didn't find links to the source code. If you can provide them, then please do it. In any case 2 other add-ons are great!

Regards,
Oksana
