### ISSUE TITLE
Professional Services Network Entry

### ISSUE THREAD

**Issue by deas** [OrderOfTheBee/marketing#30]
Hi,

we'd like to be listed at http://orderofthebee.org/professionals/ with the following entry:

Company Contentreich

Territory: Germany

Wir sind Andreas und Sandra: Seit 2006 IT Freelancer aus Hamburg mit Schwerpunkt Alfresco. Wir unterstützen in allen Phasen eines Projektes, machen aber auch kurze Support-Gigs wenn mal ganz schnell nur ein Problem gelöst werden muss.

Grundsätzlich soll das Ergebnis unserer Arbeit Menschen schnell(!) begeistern. Eine effektive Feedback-Kultur ist uns sehr wichtig. Ganz wichtig ist uns, dass der Audio-Kanal gut funktioniert -  schlicht weil er oftmals am effektivsten ist. Vertrauen ist dabei essentiell. Mit diesen Vorausetzungen klappt es in der Regel hervorragend auch über große räumliche Distanzen.

Wir arbeiten mit sehr kurzen Iterationen und streben an dabei möglichst wenig(!) Code zu produzieren. Denn wenig Code hat wenig Fehler und braucht wenig Pflege. Wir wollen zügig Mehrwerte schaffen die sofort produktiv genutzt werden können. Über die Jahre ist so ein Zoo aus über hundert Alfresco "Add-Ons" entstanden.

Wir sind gnadenlos ehrlich. Das ist nicht immer einfach.

Blog / Website : https://www.contentreich.de

Github Repos:

https://github.com/deas/contentreich-alfresco-datalists
https://github.com/deas/contentreich-eml
https://github.com/deas/contentreich-ecm-google-ms

Add-Ons:

https://www.contentreich.de/category/contentmanagement/alfresco/contentreich-add-ons

**Comment by aviriel** [comment]
Hi Andreas,

Could you please provide abstract in English? As far as all OOTBee resources are in English, all information in Professional Services Network is in English too. You can give a link to German text in the end of abstract.

**Comment by deas** [comment]
Ok, here come an English version:

We are Andreas and Sandra, and we are IT freelancing from Hamburg focused on Alfresco since 2006. We support all phases of a project, but we also give short support gigs in case there is a problem which needs to be fixed quickly.

We emphasize on shipping value quickly 🚀 using very short iterations. Effective communication matters a lot. We think it is crucial to leverage audio and even video frequently, because it just works best. With good communication in place, distance is rarely an issue.

Code has issues and maintenance is boring. That's why we aim at producing as little code as possible.

Over the years, we built a zoo of more than 100 add-ons/tweaks we maintain today.

We are very honest. Even if we expect disagreement or deal breakers.

[Blog / Website](https://www.contentreich.de)

Github Repos:

[Datalist Extensions for Alfresco Share](https://github.com/deas/contentreich-alfresco-datalists)
[Contentreich Alfresco RFC822/EML tweaks](https://github.com/deas/contentreich-eml)
[Alfresco Google Vision (Micro Service Edition)](https://github.com/deas/alfresco-google-vision)
[Google Vision MicroService](https://github.com/deas/contentreich-ecm-google-ms)

Add-Ons:

[Various Add-Ons](https://www.contentreich.de/category/contentmanagement/alfresco/contentreich-add-ons)

**Comment by aviriel** [comment]
Added with https://github.com/OrderOfTheBee/OrderOfTheBee.github.io/commit/e54933c4939a466827bdd155a32f16e5037c89d6
I added "company" label, but I'm not sure that it's correct if summary starts with "We are Andreas and Sandra, and we are IT freelancing...". But I cannot say just "Freelancer"  because there are 2 of you :)

**Comment by deas** [comment]
Thanks Oksana!

But the rocket broke. 😢

Could you please replace `:rocket:` with

`<g-emoji alias="rocket" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f680.png"><img class="emoji" alt=":rocket:" height="20" width="20" src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f680.png"></g-emoji>
`

Thanks and have a nice weekend!

**Comment by aviriel** [comment]
Fixed. Have a nice weekend too :)
