### ISSUE TITLE
Please add ecm4u to the professionals list

### ISSUE THREAD

**Issue by hi-ko** [OrderOfTheBee/marketing#32]
Hi Oksana,
would you please so kind to add also our company to the professionals list?
We should definitely also add success stories since we could tell many of them but haven't written them down with our customers ... 

Cheers
Heiko

Flag: Company

Territory: Germany

ecm4u is a company focused on and specialized in solutions for document management, process and case management based on Alfersco in any flavor. ecm4u supports many organisations in running, maintaining and extending their Alfresco system (either Community or Enterprise) for small to very large systems and maintains it's own "ecm4u Alfresco Virtual Appliance" to make install, maintenance and support easier and better. Patches we create for our community support customers find their way into our public patch Repositories.

Beside Alfresco support, consulting and remote management the ecm4u team develops products and solutions which makes Alfresco more usable in business processes and use cases.

Open Repositories:

    "Alfresco Platform 5.2.e patched":https://github.com/ecm4u/community-edition-5.2.e-patched
    "Alfresco Share 5.2.d patched":https://github.com/ecm4u/share-5.2.d-patched
    "Alfresco Platform 5.1.g patched":https://github.com/ecm4u/community-edition/tree/5.1.g-patched
    "Alfresco Share 5.1.g patched":https://github.com/ecm4u/share/tree/5.1.g-patched

Website: http://www.ecm4u.de/ and http://www.ecm-market.de

**Comment by yregaieg** [comment]
Hello @hi-ko ,
Sorry for the delays in addressing your request, I only came aware of it now, can you confirm the info in https://github.com/OrderOfTheBee/OrderOfTheBee.github.io/pull/19 to be fit for merge into master ?
Regards,
Younes

**Comment by hi-ko** [comment]
Hi Younes,
confirmed  - please go ahead and merge into master.
Thanks for taking care!
Heiko

**Comment by yregaieg** [comment]
Done, the change should be made available in few minutes unless the ongoing github issues cause more delays
