### ISSUE TITLE
Professional Service: Add Request

### ISSUE THREAD

**Issue by LeoMattioli** [OrderOfTheBee/marketing#33]
Good morning,
I would like to have my company listed in the Professional Services Network.
We are being Alfresco Partner for 8 year and we have some Alfresco Certified employee.
We don't have a customer success story, but I think we can arrange a couple.
This is our Github Channel
https://github.com/CASTGroup
We have made a couple of opensource addons:
- alfresco-inboxes (based on the project by Paolo Predonziani): we migrate to version 4.x to 5.x
- outlook plugin (based on the project by EisenVault): we added the configuration tab to permit end user customizations.

We are in Italy, we are mainly system integrators.
This is the presentation
"CASTGroup, operating since 1988, began its work creating integrated systems for the business computerisation (IT for Enterprise Solutions). Today it counts over 75 highly qualified assets.

CASTGroup is cutting edge of the design of complex systems and of the creation and implementation of reliable technical solutions for any business requirement. The achieved results are proved by the trust that important industrial and banking groups  have placed in the company."

**Comment by yregaieg** [comment]
Hi @LeoMattioli,
Not sure if you have seen this snippet in the professional services network section on our website :

> Many companies are looking for a team or a person who can implement a project based on Alfresco Community Edition. Or perhaps they need help to develop an extension or solve some specific task. Alfresco Software forbids partners to do paid work on Alfresco Community Edition, so it can be difficult to find an experienced, reliable team to help with Community Edition.
> To address this, we are forming a list of well-known systems integrators and freelancers all over the world who can help you with Community Edition.

Not sure if you can actually do Community Edition integration with your partner status.

Anyway, if you would like to have your company listed on our PSN page as a system integrator for Alfresco Content Services Community Edition, feel free to issue a PR against : https://github.com/OrderOfTheBee/OrderOfTheBee.github.io/blob/6f10b0a26d65f5aa51b328c1439db421301e0814/assets/data/psn.json

**Comment by LeoMattioli** [comment]
Thanks Younes!
I'll check the contract.
